version: '3'

services:
  db-hallazgos:
    env_file:
      - .env.development
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      - TZ:America/Mexico_City
      - PGTZ:America/Mexico_City
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: hallazgos_container
    volumes:
      - ./postgres:/var/lib/postgresql/data
